### ISSUE TITLE
Collaborative Tree Editor Example?

### ISSUE THREAD

**Issue by theronic** [y-js/yjs#106]
A lot of data structures can be modelled as trees. Would love to see an example implementation of conflict-free trees. When editing the same node (let's say it's text), can fall over to general text conflict resolution.

**Comment by dmonad** [comment]
You can model any kind of tree using YMap and YArray because types can have other types as chidren. This is also YXml works. A Xml Element is an Node that has a set of properties (modeled as YMap) and children (modelled as YArray). A child can also have children..

Does this answer your question?

**Comment by theronic** [comment]
The documentation mentions support for trees. I'm specifically interested in an **example** of how to do this.

**Comment by dmonad** [comment]
Be creative @theronic . A tree is a set of nodes in which every node has children. Children are not connected to any parent. So YMap is already a tree structure:

```js
Y({ ..
  share: {
    treeRoot: 'Map'
  }
}).then(function (y) {
  // add a child
  y.share.treeRoot.set('child', Y.Map)
  // add a child to the child
  y.share.treeRoot.get('child').set('child_child', Y.Map)
})
```

The same is obviously true for arrays. Arrays can be nested. So every Array can have a set of child-arrays. This is also a tree structure.

You can also use a combination of YMap and YArray to model your tree. Because trees are such an easy structure, it is possible to model any kind of tree with YMap and YArray. But there is no recommended way to do so..
