### ISSUE TITLE
Wire protocol/spec for replication logic and output?

### ISSUE THREAD

**Issue by csuwildcat** [y-js/yjs#116]
We are looking at Y for an open source project, but were hoping Y had a wire protocol/spec that can stand alone from this implementation, in case someone wanted to write another implementation in another language the produce the same, consistent results/output. If you don't have something like this yet, would you consider writing one up?

**Comment by dmonad** [comment]
Hi @csuwildcat sorry for the late answer.

At this point I don't want to lock-in the Yjs encoding strategy and CRDT implementation. In the future there will be Y implementation in different languages - including documentation to do this in your favorite language. But not yet.

However, it is possible to write a client that does not understand the CRDT implementation. [Ydb](https://github.com/y-js/ydb) is a server backend for Yjs, that does not understand how to decode the data. If you are still interested, I will write down how this works.

This issue is pretty old now, but my offer still stands..
