### ISSUE TITLE
YText#toDelta ignores embeds

### ISSUE THREAD

**Issue by calibr** [y-js/yjs#124]
YText#toDelta doesn't include embeds in the returning delta, but they are stored fine in the underlying structure

As far as I can see here it takes into account only ItemString and ItemFormat structs:
https://github.com/y-js/yjs/blob/master/src/Types/YText/YText.js#L550-L561

**Comment by dmonad** [comment]
I'd be happy to receive a PR for this

**Comment by calibr** [comment]
@dmonad I can submit a PR for this, but I can't run tests on the latest yjs, it breaks with error:

```
./tests/index.js → dist/tests.js...
[!] Error: Could not load /Users/denis/wrk/modules/yjs/../lib0/testing.js (imported by /Users/denis/wrk/modules/yjs/tests/index.js): ENOENT: no such file or directory, open '/Users/denis/wrk/modules/yjs/../lib0/testing.js'
Error: Could not load /Users/denis/wrk/modules/yjs/../lib0/testing.js (imported by /Users/denis/wrk/modules/yjs/tests/index.js): ENOENT: no such file or directory, open '/Users/denis/wrk/modules/yjs/../lib0/testing.js'
    at /Users/denis/wrk/modules/yjs/node_modules/rollup/dist/rollup.js:17992:19
```

Is it ok if I submit a PR without tests or how to get the tests work?

**Comment by dmonad** [comment]
Thanks, that would be great! 

I define custom import paths in `./rollup.config.js`. I uncommented the custom import paths and will keep them optional in the future. Please pull `master` and try again.

**Comment by calibr** [comment]
I submitted a PR.

Just curious, why to use a custom testing framework if there are seems to be lots of alternatives?

**Comment by dmonad** [comment]
That is an excellent question. Implementing a CRDT correctly is really hard and error prone. When you take the CRDT algorithm from a paper, it is really easy to port it to an implementation and you can be pretty sure that it is correct. But there is a lot of magic that is happening around it: E.g the order in which transformations are applied, the dependency graph of operations, or the event system interacting with the operations.. And you need to consider all possible orders of incoming changes. 

Something that worked very well for me is to simulate peers that randomly generate input. And this is what `lib0/testing` is really good at. I used other testing frameworks like mocha and AVA in Yjs before. But implementing this randomized testing approach around them wasn't really worth it. One of the most valuable things in Yjs are its tests. And since Yjs is so reliant on how it does testing, I started to implement my own testing approach. I think I started about two years ago with [cutest](https://github.com/dmonad/cutest) and now ported it to lib0.

**Comment by dmonad** [comment]
I will close this ticket since you fixed it in #153

**Comment by ISNIT0** [comment]
Looks like when this was fixed, attributes weren't added to the delta. 😢

**Comment by ISNIT0** [comment]
Made a separate issue: https://github.com/yjs/yjs/issues/187
