### ISSUE TITLE
Delete structs are not sent when a client submits deletes with sync step 2

### ISSUE THREAD

**Issue by calibr** [y-js/yjs#140]
I have experienced a situation when some client goes offline, adds an item to a YArray and then deletes it and then goes online again, after the client sends sync step 2 to a websocket server, this server broadcasts only ItemJSON struct to other clients. Hence these clients have an item in the array which shouldn't have existed. Only after resync they receive actual state from the server and delete this item.

Probably the server should have sent a DeleteStruct for the delete?

I made a simple app that reproduces this issue:

https://github.com/calibr/ytestapp

You can find instructions how to run it in the readme file.

**Comment by calibr** [comment]
I replaced `deleteItemRange` with integration of Delete structs here https://github.com/calibr/yjs/blob/master/utils/DeleteStore.js#L247-L250 and here https://github.com/calibr/yjs/blob/master/utils/DeleteStore.js#L256-L259 and it seems to have fixed my problem, but I am not sure if it has any bad side effects on Yjs and its sync system. @dmonad I am not sure why `deleteItemRange` is used instead of Delete structs there, but if my changes are beneficial for Yjs I can submit a PR.

**Comment by dmonad** [comment]
Thanks for reporting this. You are absolutely correct that a delete struct should be created instead.

Some time ago this was not necessary because structs were marked as deleted when they were encoded. It troubles me that I haven't encountered this issue before. This issue does not affect the test suite because every client syncs with every other client, so every client will eventually receive the delete struct.

I'm currently restructuring the project. Let me commit my changes, then I will address this issue.

**Comment by calibr** [comment]
@dmonad right, thanks for the answer

**Comment by dmonad** [comment]
This problem is fixed in v13.0.0-80. 

Delete is not a struct anymore, but is always sent as part of a DeleteSet instead. I completely reworked how structs and deletes are applied to the document.
