### ISSUE TITLE
Delete callback?

### ISSUE THREAD

**Issue by omaressameldin** [y-js/yjs#143]
Hi there I am trying to integrate Yjs into React, and so far everything is working well but I wanted to do some delete actions on unmount and then destroy like this when `unmounting` a component:
```
  async componentWillUnmount() {
    const { y } = this.state
    if (y.share.users.keys().length === 1) {
      y.share.textfield.delete(0, y.share.textfield.toString().length)
    }
    y.share.users.delete(this.props.auth.userId)
    await y.destroy()
  }
```
but this results in this error:
<img width="751" alt="screenshot 2019-02-25 at 09 35 57" src="https://user-images.githubusercontent.com/10829786/53324438-15707780-38e1-11e9-8971-8ae36cf718f0.png">

Doing it this way works though but it's not clean:
```
  componentWillUnmount() {
    const { y } = this.state
    if (y.share.users.keys().length === 1) {
      y.share.textfield.delete(0, y.share.textfield.toString().length)
    }
    y.share.users.delete(this.props.auth.userId)
    setTimeout(() => y.destroy(), 0)
  }
```
Do you know why the first approach fails or maybe how to fix it?
Thanks!

**Comment by dmonad** [comment]
That makes sense. You delete content (`y.share.textfield.delete(0, y.share.textfield.toString().length)`) and immediately after that you call `y.destroy()`.

The delete action is triggers the connector to send the content to the other clients in the next event-loop tick. But since you immediately destroy the yjs instance, the connector has no chance to do that.

I think you are doing the right thing here. You should even wait a bit longer to make sure the connector has enough time to transmit the content, before you call `y.destroy()` - which forces the connector to disconnect immediately.

**Comment by omaressameldin** [comment]
can't we add a callback function though to the delete function so that instead of waiting the callback function is called right after?

**Comment by dmonad** [comment]
This seems like a bit of unwanted overhead. I wouldn't expect the delete method to return a promise. 
The thing you are doing right now seems okay too me.

We could consider having a `whenSynced()` method to return a Promise when the client synced to other clients. I.e.

```
y.whenSynced().then(() => y.destroy())
```

Which is ultimately what you are trying to accomplish. But at the present it is unlikely that we can restructure all the connectors to support this. Definitely something that I'd like to have in the future though.

Closing now. Feel free to ask follow ups in the closed thread.

**Comment by omaressameldin** [comment]
The whenSynced approach sounds good to me I will leave my current implementation and of that feature is added in the future I will update my code. Thanks a lot though for the quick replies!
