### ISSUE TITLE
Compared to Automerge

### ISSUE THREAD

**Issue by pdiveris** [y-js/yjs#145]
Hi,

First of all apologies for introducing this as an issue as it's really a question and I appreciate that you might be very busy. I am working on fetching a document, doing some stuff with it and storing it, whilst taking into consideration that someone else might be working on the same document somewhere else, etc. Just like your very nice example. I've made a proof of concept with Automerge and then I bumped into your framework - for some reason I got convinced that it's worth giving it a go. I am not using a decentralised transport, I am fiddling with SSE/mercure, as it suits my particular needs. Before I embark onto re-coding it, and it seems to me that it might take some effort, I'd like to ask you if you could point out how's this conceptually different to Automerge. Or to put it differently, should I expect it to be faster/more scalable/more accurate? 

Feel free to close this as irrelevant and please do say if you've never heard of Automerge before - not a problem. I just thought I'd ask before I embark on re-writing!

Thank you for any time you put into answering.

**Comment by dmonad** [comment]
You are welcome to ask about the differences. This is what the question tag is all about :wink: 

I don't have much experience with automerge. If I understand correctly, automerge was primarily build for sharing application state. They decided to make application state immutable, and therefore it nicely integrates into react applications.

Yjs was primarily build for shared editing on text and rich-text. Yjs exposes state as mutable data types. State is mutable by design, because some computations can be done more efficiently on mutable objects. 

I would argue that Yjs is the better choice if you plan to share huge (text / rich-text) documents, because 1. its algorithm is specifically designed for shared editing and 2. it encodes its structure very efficiently in a binary format. Automerge on the other hand might be easier to handle because state changes are just operations on the shared document. I.e. 

```js
let history = Automerge.getHistory(doc2)
Automerge.diff(history[2].snapshot, doc2) // get all changes since history[2]
// [ { action: 'set', type: 'map', obj: '...', key: 'x', value: 1 },
//   { action: 'set', type: 'map', obj: '...', key: 'x', value: 2 } ]
```

If you are not working on a shared editing application and you are not hitting any performance problems, then you are probably fine with automerge. Otherwise you should definitely consider Yjs.

**Comment by pdiveris** [comment]
Ouch, I didn't pay attention to the labels ;o) Thanks for the reply, I'll give it a go as it is all about collaborative editing. You are right that Automerge is easier to handle, it's exactly the code you posted above that I had in mind when i said that it seems to me that it may take some effort to use Yjs, but I will give it a go. I am taking the liberty to close the issue, satisfied as I am with your reply, and will post my comments in one form or another when I have first hand experience on the migration.

**Comment by dmonad** [comment]
Related to this thread: I created a set of benchmarks to compare Yjs with Automerge https://github.com/dmonad/crdt-benchmarks
