### ISSUE TITLE
Update values in y-array (list structures)

### ISSUE THREAD

**Issue by cphyc** [y-js/yjs#16]
Their should be an update(position, newValue) function for ListManager.

**Comment by DadaMonad** [comment]
Of course, I could implement this by making this a shorthand for delete&insert. But this won't preserve the semantics of the action (If two users update the same element, the result would hold both updates). I think that it would be possible to implement update functionality for elements in the ListManager, but since implementing it is quite complicated, I'll only implement it when it is very much needed. For now, you can realize this by implementing delete&insert. I'll implement this someday in the future.

**Comment by AquiGorka** [comment]
>I'll only implement it when it is very much needed

+1

**Comment by dmonad** [comment]
I still want this feature. But there hasn't been much traction to get this implemented.

Closing for now..

**Comment by Amorim33** [comment]
This feature would be great @dmonad 

May I try to implement it?

**Comment by dmonad** [comment]
This feature is much harder to implement than you might think. Sure, you can try. But I expect that `update` is safe for concurrent use (multiple users updating the same item will result in only one updated item, not more). The implementation must also not add any additional properties to the Item class.
