### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by cbbfcd** [y-js/yjs#164]
Thanks for paying for this repository, this is a great implementation
I have a project that considers using Yjs, but I read the author's paper, which is still full of confusion for me, especially the reasoning process of the rule, and the specific implementation, which is a black box for me, can have more relevant information or blogs. Is it available?

**Comment by dmonad** [comment]
@cbbfcd I feel the same way. As we show in the paper, the algorithm is solid. But the reasoning behind the linked list approach is very hard to explain because it is based on a visual interpretation. So we decided to just omit the reasoning and jump straight to the proof. If you are really interested in the reasoning behind the rules, I'd be happy to give you a short explanation on my whiteboard (via conference call) - feel free to write me via mail for that. Unfortunately, I don't have the time and resources to publish an updated paper.

**Comment by cbbfcd** [comment]
thank you very much, i will write a mail to you.
