### ISSUE TITLE
Allow quick switching of rooms

### ISSUE THREAD

**Issue by AlexRuppert** [y-js/yjs#40]
It would be nice to have a method like
```
yjs.switchRoom('roomname')
```
to switch the room of the current instance.
An optional parameter should allow to decide, whether to copy the current state over to a not yet existing room, or to create the new room's state completely from scratch.

**Comment by Joeao** [comment]
Wouldn't you gain the control you desire by creating your own switch room function which stores the data, leaves the room and joins a new room outside of YJS?
Do you have a particular use case in mind?

**Comment by AlexRuppert** [comment]
In theory yes, but it it is not straightforward. I currently don't see a way do change the room, without initializing a completely new yjs instance. Also this seems not to work completely in some cases. I have created a minimal example with YText:
```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title></title>
  <meta charset="utf-8" />
</head>
<body>  
  <script src="bower_components/yjs/y.js"></script>
  <script src="bower_components/y-map/y-map.js"></script>
  <script src="bower_components/y-array/y-array.js"></script>
  <script src="bower_components/y-text/y-text.js"></script>
  <script src="bower_components/y-memory/y-memory.js"></script>
  <script src="bower_components/y-websockets-client/y-websockets-client.js"></script>
  <script>window.module = {};</script>

  <div id="room-number"></div>
  <input type="text" id="content" value="test"></div>  
  <div>
    <button onclick="gotoRoom(1)">goto room1</button>
    <button onclick="gotoRoom(2)">goto room2</button>
  </div>
  <script>    
    function gotoRoom(number){
      setUpRoom('switchRoomTest_'+number);
    }
    function setUpRoom(room) {
      if(window.yjs) {
        yjs.share.text.textfields=[];
      }
      Y({
        db: {
          name: 'memory',           
        },
        connector: {
          name: 'websockets-client',
          room: room            
        },
        sourceDir: '/bower_components',
        share: {
          text: 'Text'
        }
      }).then(function (y) {        
          window.yjs=y;
          document.getElementById('room-number').innerHTML = y.connector.options.room;
          yjs.share.text.bind(document.getElementById('content'));          
      })
    }
    gotoRoom(1);
  </script>
</body>
</html>
```

1. Open the html page with two browser instances (A and B)
2. When both in room switchRoomTest_1, the synchronization works as expected.
3. When switching both rooms in A and B to  switchRoomTest_2 via the respective button, it works as well.
4. Now go in A to room switchRoomTest_1 and in B to room switchRoomTest_2: When typing, the text of A appears in B although they are both in different rooms.

I'm not sure if this just a problem in YText or of Yjs.

As for data 'migration': My personal use case involves rooms where people can collaboratively configure a tool that displays graphs. If I want different groups to be able to have different configurations, it would be nice to have them switch rooms on the fly. Also copying an existing configuration and modifying it independently would be more comfortable, letting them create everything back from scratch.

As for additional use-cases:
- White-Boards, where you clone the content and continue on your own
- Graphs, that model something, like a Flow-Chart, where you want to make an own version without modifying the original
- etc

I think the important aspect here is a clean and easy way to switch rooms. Data migration can be done externally, if necessary, I just mentioned it as an additional idea as it is related to room switching.

**Comment by istvank** [comment]
A typical use case for switching the room would be single-page Web applications. For example there could be a document editor with a list of documents on the left. After selecting a specific document, the editor on the right could sync only the selected document.

To put it in other words, I think the problem might simply be that Yjs cannot be gracefully disconnected without having binds floating around. Or am I wrong here?

**Comment by DadaMonad** [comment]
I see the point for switching rooms. I just think it is a weird concept (one that doesn't exist in the real word). A room should contain only the specified content, not content from other rooms. There are also another issue: The room to switch to may not be empty. Therefore, the existing operations in the forked room may have an id, that is already assigned to an operation of the existing room. This problem is non-trivial, and you should really know what you are doing when you do this. This is why I won't provide an easy-to-use method for this, because it may imply that it is fully supported.

@istvank 
> To put it in other words, I think the problem might simply be that Yjs cannot be gracefully disconnected without having binds floating around. Or am I wrong here?

That's also a problem. Currently there is only a `.disconnect()`. And I can't destroy the binds because there is also a `.reconnect()`. I opened a new issue #42 for this. This should be easy to fix

@AlexRuppert 
But I will give you a solution for you request:
You could simply copy the complete content of the existing room:
```
 // apply this on the existing y1 object (lets call this y1)
 var requestAllContent = new Promise(function (resolve) {
    y1.db.requestTransaction(function * () {
      var operationsStoreContent = yield* this.getOperations()
      var deleteStoreContent = yield* this.getDeleteSet()
      resolve({
        operationStoreContent: yield* this.getOperations()
        deleteStoreContent: yield* this.getDeleteSet()
      })
    })
  })
```
And apply it on the new room
```
// apply this on the new y object (call it y2)
requestAllContent.then(function (content) {
  y2.db.requestTransaction(function * () {
    yield* this.applyDeleteSet(content.deleteStoreContent)
    yield* this.store.apply(content.operationStoreContent)
  })
})
```

This will also work if two users will do this at the same time. I haven't tested this, so write me if this doesn't work for you (it almost definitely should though). But you have to make sure that the room does not contain any content from a previous session (one that is a fork of y1)

As a side note: You should cross-compile this with Babel, because it uses Generators.
