### ISSUE TITLE
for...in loops cause errors

### ISSUE THREAD

**Issue by istvank** [y-js/yjs#46]
In https://github.com/y-js/yjs/blob/master/src/Database.js#L217 you loop over an array which could have properties defined.

In my case, a 3rd party library is defining properties on Arrays which cause Yjs to fail. Miserably. :smiling_imp:

**Comment by DadaMonad** [comment]
Well reported!

> you loop over an array which could have properties defined

Actually, I define this Array you are talking about. And I always make sure that my Arrays never have properties. Because an Array is an Array, not an Object.

The reason for this problem is (probably) that one of your libraries overwrites a function on Array.prototype, which in turn puts weird properties on my beautiful, well defined Arrays :( 

Since this was already mentioned, I'll fix this problem by removing all my for.. in loops. I don't wanna judge people who use weird Array.prototype magic (plz don't do that ever).

**Comment by istvank** [comment]
:+1: Thank you! :thumbsdown: for :japanese_ogre: applying weird Array.prototype magic... :smile:

**Comment by istvank** [comment]
Is it the same issue here? https://github.com/y-js/yjs/blob/master/src/Database.js#L273

**Comment by DadaMonad** [comment]
No, that `for.. in` loop iterates over an Object.
