### ISSUE TITLE
SyncMeta model updates to certain elements sometimes stop being applied in Yjs

### ISSUE THREAD

**Issue by junpls** [y-js/yjs#54]
This issue is related to both Yjs and SyncMeta. **I'm using the default Yjs (fallback) server**.
When loading a model into a SyncMeta instance via the Import Tool (former Debug Widget), it might happen, that certain elements in it "break", by the means, that the changes you apply to them will be present in the local Yjs representation, but won't be propagated to other clients. Those excact elements will stay broken, even if you refresh the page or delete and re-import the model.

The error is hard to reproduce, as it is very rare, and hard to notice once it happens. Atm, I can't think of another way then importing a model over and over again, then moving around random nodes, in oder to see if they change on another client too.

[errormodel.zip](https://github.com/y-js/yjs/files/450776/errormodel.zip)

**Comment by DadaMonad** [comment]
Which version are you using?

**Comment by DadaMonad** [comment]
This is exactly the behavior you get when messages get lost. So this is what I think is happening:

You create a rather big set of nodes. These nodes may contain additional shared elements (e.g. text). Synce creating types in Yjs < 12 is asynchronous, most of the types are created in different functions in the event loop. I.e. the following cases differ:

```
// case 1
y.map.set('1', Y.Text)
y.map.set('2', Y.Text)
// creates one messages that is sent with the connector (in your case with websockets)

// case 2
setTimeout(function () {
  y.map.set('1', Y.Text)
}, 0)
setTimeout(function () {
  y.map.set('2', Y.Text)
}, 0)
// creates two messages that are sent with the connector
```

Because you create so many types (types that contain types), you send too many messages and messages get lost. I really can't do anything about that. Now I come to my solution which is really cool: In Yjs@12.0.1 I implemented a protocol to detect incorrect states and automatically resolve them. Anyway, because Yjs@12 type creating is synchronous, you shouldn't create too many messages.

I think you wanted to upgrade anyway. If you don't I could implement this feature for the version you are using.

**Comment by DadaMonad** [comment]
You can now upgrade to v11.2.6 or v12 which will fix the issue.
