### ISSUE TITLE
"i" redeclared in Struct.js

### ISSUE THREAD

**Issue by fbernhard** [y-js/yjs#61]
The variable "i" is declared twice in the same function, once with "var" and once with "let". 
This fails in iOS using Ionic2. 

https://github.com/y-js/yjs/blob/master/src/Struct.js#L132
https://github.com/y-js/yjs/blob/master/src/Struct.js#L272

I would suggest to not re-declare the variable on line 272.

**Comment by dmonad** [comment]
While I agree that this is bad code style, it is actually syntactically correct. The `let` assignment has its own scope (because it is nested in a block).

Since you reported this issue I assume that you use Yjs from npm, and somehow serve it to Safari. Some npm packages use EcmaScript features only available in Node - so do I. Therefore, you should run [babel](https://babeljs.io/) before you serve it to the browser. Another option would be to use the bower package, as it already contains a babelified version of Yjs.

Nevertheless, I'm going to fix this.

**Comment by fbernhard** [comment]
We use Yjs as an npm module in a Typescript/Angular2/Ionic2 project. We run it through Babel for the web, we have only encountered the problem when we have built the project for Ionic. I am not sure how the Ionic build process works in details. 

Thanks for changing it.
