### ISSUE TITLE
Support for PubSub communication protocol

### ISSUE THREAD

**Issue by Flaminator89** [y-js/yjs#63]
I've been looking at the examples and was wondering whether or not support for a pubsub communication protocol would be something that could be implemented?  I am interested in building a connector which would allow hooking up to a a pubsub protocol delivered over wamp (such as crossbar/autobahn).  I hope this is the right spot to post this question, if not feel free to close/delete!

**Comment by dmonad** [comment]
Sure, this should be possible. But there has to be a way to get the current state of the shared data. This is usually done using directed communication. I suggest to implement a server for getting the initial content. When the iniatial sync process is done you can send & receive updates from the pubsub. Or do you have something different in mind?

**Comment by Flaminator89** [comment]
Nothing in mind yet! :)  I think I understand what you mean.  The client, after being disconnected for a while has missed the published messages and so needs to sync up (so client does an http-request, and receives a response with the most recent content) before relying on PubSub.  Is this what your thinking would work best?  Would the client have any problems doing the conflict resolution in this situation?  I'm not sure if it will help us at all, but remote procedure calls are also supported over wamp.

**Comment by dmonad** [comment]
That's right. I think that would be the best solution. Let me brag a little bit: Something like this would hardly be possible using Operational Transformation **. Yjs is pretty unique because it doesn't need a central place to transform operations (changes on the document). One of my goals was to design a framework that works with any communication protocol.

I suggest you have a look at [y-websockets-server](https://github.com/y-js/y-websockets-server), and [y-websockets-client](https://github.com/y-js/y-websockets-client). You basically just have to overwrite the `broadcast` method, and make sure to call `receiveMessage(..)` when a message from PubSub arrives. If your PubSub implementation also supports directed communication, you can even do without websockets. And to make this clear: it is completely fine for the clients to broadcast messages using PubSub. You only need the server to maintain state, and for the initial sync process with the clients (or when reconnecting).

Some time ago I implemented something very similar using XMPP ([y-xmpp](https://github.com/y-js/y-xmpp)). But I used MUC in favor of XMPP-PubSub, because the permission handling was difficult.

** Actually there are some approaches with similar characteristics, but very bad runtime behavior.

**Comment by Flaminator89** [comment]
Sounds good, I will have a look at the websockets examples connectors and see if I'm able to put one together for a pubsub communication.  So if I understand the underlying protocol used by y-js it's more similar to WOOT?  or does it use CRDT's?

Unrelated : I found I'm getting an error a npm install warning (unmet peer dependency yjs 12.0.4) as I'm trying to get this running on heroku... could be something silly but have you seen that before?  Do you have an example with a package.json I could take a look at to get going?

**Comment by dmonad** [comment]
We recently published a paper about the CRDT used it Yjs: [yjs.pdf](https://github.com/y-js/yjs/files/695979/yjs.pdf) If you are familiar with WOOT: they share some similarities. 

If you can, try to ignore the peer dependency error. It happens in some versions of npm. Otherwise try to remove `y-leveldb` from package.json.

**Comment by Flaminator89** [comment]
This seems like it would be interesting to implement, but unfortunately I've decided to go a different direction in terms of communication protocol so have no plans to work on this in the near future. :)

**Comment by dmonad** [comment]
That's unfortunate. Feel free to re-open it if you plan to work on it.

**Comment by joshmarinacci** [comment]
I'm trying to adapt Yjs to a pub/sub provider (PubNub) and I'm having some trouble.  I can get the first client to connect, but when the second connects the first sends some sync data like this

```
 { type: 'sync step 1',
  stateSet: {},
  deleteSet: {},
  protocolVersion: 11,
  auth: null }
```

then the second client crashes with this:

```
  y:connector Receive 'sync step 1' from pn-ddc7f9ab-04b9-4bce-bc2d-ba32bb107c7a +262ms
  y:connector-message Message: {"type":"sync step 1","stateSet":{},"deleteSet":{},"protocolVersion":11,"auth":null,"room":"r1"} +2ms
(node:69485) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Unable to deliver message
(node:69485) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm not sure what to do.  Also, I'm confused about the p2p versus master/slave.   Other than for loading pre-existing data,  I shouldn't *need* a master, right? when calling this.receiveMessage() can I pass in the UUID of the sender and then the message payload?

thanks. This is a great lib!

**Comment by dmonad** [comment]
Hi @joshmarinacci,

The terminology master/slave is a bit misleading. The difference is that the "slaves" can only exchange data with one client. This is solely implemented to do some optimizations for client-server protocols. In the case of P2P, every client should be registered as a master.

My advice is to use [y-webrtc](https://github.com/y-js/y-webrtc) as a template. The "Unable to deliver message" message is either thrown because you incorrectly overwrote the `checkAuth` method, or you forgot to add the sending user to the list of connected clients. You have to call `this.userJoined(uid, 'master')` *before* you receive a message from user `uid`. You always have to perform a handshake before you can perform collaboration with other peers - this is what `userJoined` is for
.
