### ISSUE TITLE
The regenerator/runtime module is deprecated

### ISSUE THREAD

**Issue by boris-petrov** [y-js/yjs#64]
I get that warning in Chrome 55. The full text is:

```
The regenerator/runtime module is deprecated; please import regenerator-runtime/runtime instead.
```

**Comment by dmonad** [comment]
I will update the regenerator package when I publish the next major release. Updating it now would break all y-* modules. You can safely ignore this warning.

I'm going to close this issue when I updated the regenerator package.

**Comment by dmonad** [comment]
I'm going to close this because Yjs@v13 does no longer use regenerator

**Comment by boris-petrov** [comment]
@dmonad - great, thanks! When is v13 going to be stable and is there going to be a migration guide from v12?

**Comment by dmonad** [comment]
I've been developing v13 for 8 month now. But I don't want to publish v13 yet because a lot of people rely on y-richtext, which hasn't been ported yet. Also I plan some more breaking changes.

I really hope to release within the next two months. But no promise. When I eventually release - the documentation will be greatly improved. And, of course, I will also publish a migration guide ;)
