### ISSUE TITLE
Database storage, and repopulating the server?

### ISSUE THREAD

**Issue by NathanaelA** [y-js/yjs#82]
Ok, I have a client/server using websockets design, both clients and servers use the memory database adapter and the text adaptor.   I have found via lots of search's and looking through the source code how to get access to the final document as it stands on the server, so I can basically save this every so often back to my own permanent storage, I can also clean up and eliminate rooms after so much time being abandoned.     So I am good on this point.   ;-)

However, when a server comes up, I would like it to be able to (re)populate the rooms as they are opened with the data.    However, I can't seem to find the way to repopulate the room correctly, using `insert` will cause any clients when they reconnect to just get the new data inserted with the old.  The delete command has no "delete_all" ability that I can see, that I could fire off first.   

So my question What is the way to repopulate a room, so that when the client reconnects, it treats the master as the source of truth?  Or even better would be to be able to have the client if it has a later edit data become the source of truth and update the server copy.   I can't seem to figure out a way to do either...

**Comment by dmonad** [comment]
I recommend to treat the Yjs model as the source of truth. You can store the document to a database for indexing. But, if possible, you should never forget the Yjs model, as this is the only way clients without internet access can reliably join and sync with the server. You could use the new persistence layer (which will be in beta for the next few month) to persist the room content on the server. I am soon starting to develop a persistence layer using Google Cloud Storage, if that is interesting to you.

You can also treat the database as the source of truth. This is how I would handle it:
* Clients receive a sessionId when they connect to the server
* When a client connects without an existing sessionId, get the content from the database and create a sessionId
* When all clients disconnect, forget the room content and sessionId on the server after some timeout (e.g. 1 hour)
* When a client reconnects, use that content on the server. Furthermore, get the sessionId from the client
* When two clients with different sessionId reconnect, one of the clients should forget the room content. In this case the client will lose content - it is very unlikely if you set the forget timeout (see point 2) very high

Here is an event simpler approach:
* When a client connects to the server, the server populates the room content if empty
* When all clients disconnect, the server forgets the room content after some timeout (e.g. 1 hour)
* When a client was not able to reconnect for 40 minutes, the client must forget its local updates and start fresh (this should be enforced by the server)

When the database is the source of truth, and if you want to be able to forget the Yjs model, you will always run into cases where clients are not able to commit changes. That's not too bad in most projects. It somehow limits you, because you can't cache the document on the client using y-indexeddb. On the other hand, it is much easier to do maintaining, and do Yjs upgrades. Furthermore, most people would say that SQL is a bit more reliable than Yjs :stuck_out_tongue:

**Comment by NathanaelA** [comment]
I described what I figured out in gitter for another guy today, which seems to work, but for long term in case someone else needs it here is what I'm doing since it has taken a lot of testing and reading lots of the yjs source code and examples...  ;-)

My purpose is source code editing and the code is ran automatically on changes and synced to any other devices connected (not via yjs a totally different sync for running on the remote devices).   So the yjs model is actually worthless for everything except the source code editing.    ;-)   So I honestly don't need to save it.        I need the final rendered value; for saving and running.   ;-)       So I follow the `update` messages and then set the save timer for that room to now + 3 seconds, to create a debounce.   The debounce system is a single setInterval that fires every second and checks each room to see if the last save time  has expired; if it has, then it pulls the current value and saves it to my persistent storage (and then triggers the run system).   The timer also checks each room's delete timer to see if it has hit the time to be deleted.  So that everything stays clean.

So when the room comes up new I pull the latest copy from my persistent storage layer, and insert it into the room.   At this moment it appears that by creating a new YText per file on a Map seems to work great.   If the server crashed and comes back up; it pre-populates the room when they connect.  The data on the browser if they were typings gets resynced to the server properly and the client doesn't loose any data, which fires an "update" message and performs the persistant save and everyone is happy.      If the client went away at the same time as the server crashed; then I get the last known good value.   So far this seems to be the best of both worlds.   I have only one small case where I can lose data now.  If the person types, it is de-bounced for 3 secs.  If the server crashes at that point, the changes on the server are gone.  If they leave at the same time, loss of a number of seconds of work.    Nothing I can do **easily** about that, so I think I'm pretty happy with it.   If I find it is an issue; I do have a pretty good solution, but requires more moving pieces, so I don't think it is worth the work unless I find that users are complaining about lost work...

In Summary:
1. I use memory on both server and client.    
2. I communicate using websockets
3. I populate the server side Map->YText with the last moment of truth value from the db upon creation of the room/file.
4. I delete the room after about 1 minute of no users being connected.  But I haven't finalized the timing yet, I'm probably going to change that to 15 minutes.  The initial timing was just a guess, I didn't want to delete the room if they had a loss of internet, or refresh of the browser.
5. I am NOT making the client forget its changes, I can't stand loosing code.  ;-)    I would be fairly ticked if I fixed a bug and for some reason the server crashed and then it came up and I lost my changes.   The browser session in my opinion in this case is more important than the servers copy.

**Comment by KrishnaPG** [comment]
working on similar issue. @NathanaelA mentioned above deleting the room. Is it possible?

How to change the room on the fly? Do we have to delete the `y` object and recreate again with new room or some simpler way exists? (FWIW, tried re-initializing the `Y()` again with different room name, but its not working)

**Comment by dmonad** [comment]
Deleting rooms is possible. Calling destroy should also remove the persisted data. If you want to move the data to a different room - you need to do that yourself.. Yjs doesn't provide a mechanism for that.

**Comment by dmonad** [comment]
In Yjs@v13 I provide methods to encode and decode the Yjs model. So you are now able to repopulate the room @NathanaelA .

```
var binary = Y.utils.toBinary(y)
Y.utils.fromBinary(y, binary) // repopulates the room with the old content
```

You could now store the Yjs model in your database and repopulate when a client joins in again. The sync between server and client won't lead to conflicts if they have the same model.

@KrishnaPG This also enables you to move the content of the room around. E.g. you could populate a different room with the same data, and destroy the old room.

**Comment by dmonad** [comment]
By the way, the solution that @NathanaelA  is super valuable. Thanks for that

**Comment by Rush** [comment]
> 3\. I populate the server side Map->YText with the last moment of truth value from the db upon creation of the room/file.

How do you prepopulate the room after server crashing? When I tried `y.share.textarea.insert(0, initialText);` it actually does that the code says .. the reconnecting client gets the initial text prepended to their previous value.

**Comment by dmonad** [comment]
You can't create an repopulate y.share.textarea properly because an existing client might upload content back to the server (even if the server crashed). 

If you want the server to control the content, you could use this to repopulate the content

```
y.share.map.set('textarea', Y.Text)
y.share.map.get('textarea').insert(0, initialContent)
```

But then you'd have to wait on the client side until `y.share.map.get('textarea')` is ready

**Comment by Rush** [comment]
> But then you'd have to wait on the client side until `y.share.map.get('textarea')` is ready
Right .. waiting is not a problem. But then I probably have to nuke the client's current content manually - correct? (as in - recreate their in memory stores from scratch)  I was under the impression that @NathanaelA's solution was letting temporarily offline clients to sync back their changes.

**Comment by dmonad** [comment]
He deletes the room one minute after the last client disconnected. This allows you to be offline at least temporary.

**Comment by NathanaelA** [comment]
@rush - Yes, Kevin is correct - I leave the room alone and have a debounce timer that deletes the room after a set amount of time of all clients being disconnected.   This typically handles the temporary loss of internet without triggering any issues.    If the room is disconnected; then the client actually gets a new version of the data from the server.

**Comment by jloganolson** [comment]
@dmonad Did the Google Cloud Storage persistence layer ever happen?

(re: "I am soon starting to develop a persistence layer using Google Cloud Storage, if that is interesting to you." in 2017)
